image:
  file: .gitpod.Dockerfile
tasks:
  - init: make
  - command: |
      ocaml -version
      coq -version

vscode:
  extensions:
    - maximedenes.vscoq
    - https://github.com/capt-hb/agda-mode-vscode/raw/master/agda-mode-0.3.7.vsix