stages:
  - build

.build: &build
  stage: build
  script:
    - make
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - "src/*.glob"
      - "src/*.vo"
      - "src/.*.aux"
      - "src/*/*.glob"
      - "src/*/*.vo"
      - "src/*/*/.*.aux"
      - "src/*/*/*.glob"
      - "src/*/*/*.vo"
      - "src/*/*/*/.*.aux"

# coq-8.8:  {<<: *build, image: "skeuchel/coq:8.8"}
coq-8.9:  {<<: *build, image: "skeuchel/coq:8.9"}
coq-8.10: {<<: *build, image: "skeuchel/coq:8.10"}
