version: 2.1

defaults: &defaults
  steps:
    - checkout
    - run:
        name: Build project
        command: eval $(opam env) && opam list && make Makefile.coq && make -j2 Makefile.coq pretty-timed
        no_output_timeout: 1200
  resource_class: medium+

jobs:
  coq-8-12: {<<: *defaults, docker: [{image: "skeuchel/coq:8.12"}]}
  coq-8-13: {<<: *defaults, docker: [{image: "skeuchel/coq:8.13"}]}

workflows:
  version: 2
  build:
    jobs:
      - "coq-8-12"
      - "coq-8-13"
