version: 2.1

defaults: &defaults
  steps:
    - checkout
    - run:
        name: Build project
        command: eval $(opam env) && opam list && make Makefile.coq && make -j4 -f Makefile.coq pretty-timed
        no_output_timeout: 1200
  resource_class: large

jobs:
  coq-8-15: {<<: *defaults, docker: [{image: "ghcr.io/katamaran-project/coq:8.15.2_iris-3.6.0_equations-1.3"}]}
  coq-8-16: {<<: *defaults, docker: [{image: "ghcr.io/katamaran-project/coq:8.16.1_iris-3.6.0_equations-1.3"}]}

workflows:
  version: 2
  build:
    jobs:
      - "coq-8-15":
          filters:
            branches:
              ignore: bounded-ints
      - "coq-8-16":
          filters:
            branches:
              ignore: bounded-ints
