version: 2.1

defaults: &defaults
  steps:
    - checkout
    - run:
        name: Build project
        command: eval $(opam env) && make
        no_output_timeout: 1200

jobs:
  coq-8-8:  {<<: *defaults, docker: [{image: "skeuchel/coq:8.8"}]}
  coq-8-9:  {<<: *defaults, docker: [{image: "skeuchel/coq:8.9"}]}
  coq-8-10: {<<: *defaults, docker: [{image: "skeuchel/coq:8.10"}]}

workflows:
  version: 2
  build:
    jobs:
      - "coq-8-8"
      - "coq-8-9"
      - "coq-8-10"
